import { createClient } from 'npm:@supabase/supabase-js@2.57.4';

const ALLOWED_ORIGINS = new Set(['https://nexfrontierlogic.nz','https://www.nexfrontierlogic.nz']);
function cors(req: Request) {
  const origin = req.headers.get('Origin') || '';
  return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://nexfrontierlogic.nz','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Client-Info, Apikey','Vary':'Origin','Cache-Control':'no-store'};
}
function reply(req: Request, body: unknown, status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json'}});}
async function sha256(msg:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(msg));return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,'0')).join('');}
function salt(){const b=new Uint8Array(16);crypto.getRandomValues(b);return Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('');}
function hexToBytes(hex:string){return new Uint8Array((hex.match(/.{2}/g)||[]).map(h=>parseInt(h,16)));}
async function pbkdf2(pass:string,saltHex:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:hexToBytes(saltHex),iterations:600000,hash:'SHA-256'},key,256);const hash=Array.from(new Uint8Array(bits)).map(b=>b.toString(16).padStart(2,'0')).join('');return `pbkdf2:600000:${saltHex}:${hash}`;}
function weak(p:string){const l=p.toLowerCase();if(['password','passphrase','admin','administrator','123456789012','nf-admin-qa-passphrase-2026!'].includes(l))return true;if(l.includes('test')&&l.includes('pass'))return true;if(/^(.)\1{11,}$/.test(p))return true;const half=l.slice(0,Math.floor(l.length/2));if(l.length>=12&&half.length>=4&&l===half+half)return true;for(const w of ['password','passphrase','admin','letmein','welcome','changeme','qwerty'])if(l===w||l===w+w||l===w+w+w)return true;return /^(0123456789|123456789012|9876543210)/.test(l);}

Deno.serve(async(req:Request)=>{
  const origin=req.headers.get('Origin');if(origin&&!ALLOWED_ORIGINS.has(origin))return reply(req,{ok:false,code:'ORIGIN_NOT_ALLOWED',message:'Origin not allowed.'},403);if(req.method==='OPTIONS')return new Response(null,{status:200,headers:cors(req)});if(req.method!=='POST')return reply(req,{ok:false,message:'Method not allowed.'},405);
  try{
    const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const body=await req.json().catch(()=>({}));const action=String(body.action??'').trim();
    if(action==='request-reset')return reply(req,{ok:false,code:'LEGACY_RESET_REQUEST_RETIRED',message:'The legacy bootstrap-secret reset flow is retired. Administrator recovery must be initiated through the controlled administrator process.'},410);
    if(!['verify-token','perform-reset'].includes(action))return reply(req,{ok:false,message:'Unknown action.'},400);
    const token=String(body.token??'').trim();if(!token)return reply(req,{ok:false,message:'Reset token is required.'},422);
    const {data:row}=await supabase.from('drm_access_tokens').select('id,admin_id,expires_at,is_valid,used_at').eq('token_hash',await sha256(token)).eq('token_type','admin_passphrase_reset').maybeSingle();
    if(!row)return reply(req,{ok:false,code:'INVALID_TOKEN',message:'Invalid reset token.'},403);if(!row.is_valid||row.used_at)return reply(req,{ok:false,code:'TOKEN_USED',message:'This reset link has already been used.'},403);if(new Date(row.expires_at)<new Date()){await supabase.from('drm_access_tokens').update({is_valid:false,invalidated_at:new Date().toISOString()}).eq('id',row.id);return reply(req,{ok:false,code:'TOKEN_EXPIRED',message:'This reset link has expired.'},403);}
    const {data:admin}=await supabase.from('drm_admins').select('id,name,email,role,admin_status').eq('id',row.admin_id).maybeSingle();if(!admin||admin.admin_status!=='active')return reply(req,{ok:false,code:'ADMIN_NOT_ACTIVE',message:'This admin account is not active.'},403);if(action==='verify-token')return reply(req,{ok:true,admin:{name:admin.name,email:admin.email,role:admin.role}});
    const pass=String(body.newPassphrase??'').trim();const confirm=String(body.confirmPassphrase??'').trim();if(!pass||!confirm)return reply(req,{ok:false,message:'New passphrase and confirmation are required.'},422);if(pass.length<12||weak(pass))return reply(req,{ok:false,message:'Choose a stronger passphrase of at least 12 characters.'},422);if(pass!==confirm)return reply(req,{ok:false,code:'PASSPHRASE_MISMATCH',message:'Passphrases do not match.'},422);
    const {data:consumed,error}=await supabase.from('drm_access_tokens').update({used_at:new Date().toISOString(),is_valid:false,invalidated_at:new Date().toISOString()}).eq('id',row.id).eq('is_valid',true).is('used_at',null).select('id').single();if(error||!consumed)return reply(req,{ok:false,code:'TOKEN_USED',message:'This reset link has already been used.'},403);
    await supabase.from('drm_admins').update({passphrase_hash:await pbkdf2(pass,salt()),failed_login_attempts:0,locked_until:null}).eq('id',admin.id);const now=new Date().toISOString();await supabase.from('drm_access_tokens').update({is_valid:false,invalidated_at:now}).eq('admin_id',admin.id).eq('token_type','admin_session').eq('is_valid',true);await supabase.from('drm_access_tokens').update({is_valid:false,invalidated_at:now}).eq('admin_id',admin.id).eq('token_type','admin_passphrase_reset').eq('is_valid',true).is('used_at',null);await supabase.from('drm_audit_events').insert({event_type:'ADMIN_PASSPHRASE_RESET_COMPLETED',admin_id:admin.id,event_metadata:{mechanism:'controlled_reset_token',role:admin.role}});return reply(req,{ok:true,message:'Passphrase updated. Please sign in again.',admin:{name:admin.name,email:admin.email,role:admin.role}});
  }catch(e){console.error('drm-admin-reset error',e);return reply(req,{ok:false,message:'An unexpected error occurred.'},500);}
});
